from langgraph.graph import StateGraph, START, END
from src.state import AgentState
from src.analyst_agent import analyst_agent
from src.writer_agent import writer_agent
from src.tools.analyst_tools import (
    detect_delivery_delays,
    detect_demand_anomalies,
    score_region_risk
)
import json

# Supervisor Node

def supervisor_node(state: AgentState):

    """
    Decides which agent should run next.

    Routing Logic:

    No findings  -> Analyst

    Findings exist but no report
                 -> Writer

    Report exists
                 -> END
    """

    if not state.findings:

        state.next_agent = "analyst"

    elif not state.report:

        state.next_agent = "writer"

    else:

        state.next_agent = "end"

    return state



# Analyst Node


def analyst_node(state: AgentState):
    """
    Runs the analysis tools.

    The tools generate deterministic findings.

    The Analyst LLM then reviews those findings and
    produces a short analytical summary.

    Only the tool outputs are stored in state.findings.
    """

    delivery_delays = detect_delivery_delays.invoke(
        {
            "threshold_days": 1
        }
    )
    print(delivery_delays[0])

    demand_anomalies = detect_demand_anomalies.invoke(
        {
            "z_threshold": 2
        }
    )
    print(delivery_delays[0])

    region_risks = score_region_risk.invoke({})

    print(demand_anomalies[0])


    state.findings = {

        "delivery_delays": delivery_delays,

        "demand_anomalies": demand_anomalies,

        "region_risks": region_risks

    }


    analyst_summary = analyst_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": f""" Analyze the following findings.

                    Delivery Delays

                    {delivery_delays}

                    Demand Anomalies

                    {demand_anomalies}

                    Region Risks

                    {region_risks}

                    Provide a concise operational summary.
                    """
                                    }
                                ]
                            }
                        )

    state.messages.append(
        analyst_summary["messages"][-1]
    )

    print("Analyst finished.")

    return state




# Writer Node


def writer_node(state: AgentState):
    print("=" * 80)
    print("BEFORE WRITER AGENT")
    print(state.findings["delivery_delays"][0])
    print("=" * 80)
    

    print("=" * 80)
    print("SIZE OF FINDINGS")
    print(len(json.dumps(state.findings)))
    print("=" * 80)
    result = writer_agent.invoke(

        {"messages": [{"role": "user",
                      "content": f""" These are the verified findings generated by the analyst tools.

                      {state.findings}

                       Rank them by severity.

                       Then generate a markdown executive briefing.
                       """}]})
    
    print("=" * 80)
    print("AFTER WRITER AGENT")
    print(result)
    print("=" * 80)

    last_message = result["messages"][-1]

    if isinstance(last_message.content, str):
        report = last_message.content

    elif (
        isinstance(last_message.content, list)
        and len(last_message.content) > 0
        and "text" in last_message.content[0]
    ):
        report = last_message.content[0]["text"]

    else:
        raise ValueError(
            f"Unexpected writer output format: {last_message.content}"
        )

    state.report = report

    return state



# Routing Function


def route_from_supervisor(state: AgentState):

    """
    Reads the routing decision
    written by supervisor_node.
    """

    return state.next_agent



# Graph


graph_structure = StateGraph(AgentState)

graph_structure.add_node(
    "supervisor",
    supervisor_node
)

graph_structure.add_node(
    "analyst",
    analyst_node
)

graph_structure.add_node(
    "writer",
    writer_node
)



# Start


graph_structure.add_edge(
    START,
    "supervisor"
)



# Supervisor Routing


graph_structure.add_conditional_edges(
    "supervisor",
    route_from_supervisor,
    {
        "analyst": "analyst",
        "writer": "writer",
        "end": END
    }
)



# Return To Supervisor


graph_structure.add_edge(
    "analyst",
    "supervisor"
)

graph_structure.add_edge(
    "writer",
    "supervisor"
)



# Compile


graph = graph_structure.compile()



# Test Run


if __name__ == "__main__":

    initial_state = AgentState(
        messages=[],
        findings={},
        report=None,
        next_agent=None
    )

    result = graph.invoke(initial_state)

    print("\n")
    print("=" * 80)
    print("FINAL REPORT")
    print("=" * 80)
    print("\n")

    print(result["report"])